package f95gm.domain.api

object F95Api {
    const val BASE: String = "/api"
    const val LOGIN: String = "$BASE/login"
    const val LOGOUT: String = "$BASE/logout"
    const val SESSION: String = "$BASE/session"
    const val CATALOG: String = "$BASE/catalog"
    const val CATALOG_OPTIONS: String = "$CATALOG/options"
    const val MARKS: String = "$BASE/marks"
    const val MARKS_CHECK: String = "$MARKS/check"
    const val FILTERS: String = "$BASE/filters"
    const val FILTERS_EXPORT: String = "$FILTERS/export"
    const val FILTERS_IMPORT: String = "$FILTERS/import"
    const val ITEM: String = "$BASE/item"
    const val MEDIA: String = "$BASE/media"
    const val HEALTH: String = "$BASE/health"
    const val SHUTDOWN: String = "$BASE/shutdown"
    const val FILTER_ID: String = "filterId"
    const val TAB_ID: String = "tabId"
    const val THEME: String = "theme"

    const val CATEGORY: String = "category"
    const val PAGE: String = "page"
    const val ROWS: String = "rows"
    const val SORT: String = "sort"
    const val SEARCH: String = "search"
    const val CREATOR: String = "creator"
    const val DATE: String = "date"
    const val TAG_TYPE: String = "tagtype"
    const val TAGS: String = "tags"
    const val EXCLUDED_TAGS: String = "notags"
    const val PREFIXES: String = "prefixes"
    const val EXCLUDED_PREFIXES: String = "noprefixes"
}
